### ISSUE TITLE
Add tests for CLI include

### ISSUE THREAD

**Issue by mraible** [oktadev/okta-blog#762]
Solution to try: https://github.com/colbyfayock/demo-eyes-actions-netlify/blob/main/.github/workflows/test.yml

**Comment by mraible** [comment]
@colbyfayock I tried adding Applitools and your suggested workflow in https://github.com/oktadeveloper/okta-blog/pull/771. It failed with the default timeout of 60 seconds. After bumping it to 5 minutes, I just seem to be getting 401s from Applitools. I tried updating my Applitools API key, but it still seems to have issues.

**Comment by colbyfayock** [comment]
it looks like it's failing when doing the API lookup for the batch inside of Applitools. it looks like the max-timeout on that isn't working either as it's going to keep running, I'd recommend killing that workflow

**Comment by mraible** [comment]
Yes, I have `APPLITOOLS_API_KEY` set.

<img width="923" alt="Screen Shot 2021-04-19 at 10 17 14 AM" src="https://user-images.githubusercontent.com/17892/115269354-76c6b680-a0f8-11eb-834d-2ffadfbc58d6.png">

**Comment by colbyfayock** [comment]
ill see if i can reproduce and find an answer. i'm also working on getting branch support which it currently doesnt have, meaning, that the tests use the main branch as the baseline on PR

**Comment by colbyfayock** [comment]
hey @mraible havent had a chance to spend a lot of time on this but getting back to it

i think the error is related to a configuration error I had in there for trying to make branching work inside Applitools, that should be resolved if it indeed is the same issue

I also updated my workflow in my demo: https://github.com/colbyfayock/demo-eyes-actions-netlify/blob/main/.github/workflows/test.yml

particularly, the change I made was to use an action that waits for the Netlify deploy check to finish rather than waiting for a 200. reasoning is if you're pushing a commit to an existing PR, the URL will already exist from the first deploy, so the test would kick off immediately

would love to hear your thoughts and see if that fixes the issue
